name: mvpeventstaffing
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  get:
  get_storage:

  pin_code_text_field:

  google_fonts:
  table_calendar:
  intl:
  json_annotation:


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable:
  build_runner:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/